export const styles = {
  app: { fontFamily: 'Inter, system-ui, sans-serif', minHeight: '100vh', background: '#0f1117', color: '#fff' },
  center: { display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh', background: '#0f1117', color: '#fff' },
  authContainer: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', minHeight: '100vh', padding: '20px' },
  logo: { fontSize: '2.5rem', fontWeight: '700', color: '#6366f1', margin: '0 0 8px 0' },
  tagline: { color: '#9ca3af', margin: '0 0 40px 0', fontSize: '1rem' },
  authBox: { background: '#1a1d27', border: '1px solid #2d3148', borderRadius: '12px', padding: '40px', width: '100%', maxWidth: '400px' },
  authTitle: { margin: '0 0 24px 0', fontSize: '1.25rem', fontWeight: '600' },
  input: { width: '100%', padding: '12px', marginBottom: '12px', background: '#0f1117', border: '1px solid #2d3148', borderRadius: '8px', color: '#fff', fontSize: '0.95rem', boxSizing: 'border-box' },
  button: { width: '100%', padding: '12px', background: '#6366f1', border: 'none', borderRadius: '8px', color: '#fff', fontSize: '0.95rem', fontWeight: '600', cursor: 'pointer', marginTop: '4px' },
  message: { color: '#f87171', fontSize: '0.85rem', margin: '0 0 12px 0' },
  toggle: { textAlign: 'center', marginTop: '20px', color: '#9ca3af', fontSize: '0.9rem' },
  link: { color: '#6366f1', cursor: 'pointer', fontWeight: '600' },
  dashboard: { minHeight: '100vh', display: 'flex', flexDirection: 'column' },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '16px 32px', background: '#1a1d27', borderBottom: '1px solid #2d3148' },
  headerLogo: { fontSize: '1.5rem', fontWeight: '700', color: '#6366f1', margin: 0 },
  headerRight: { display: 'flex', alignItems: 'center', gap: '16px' },
  userEmail: { color: '#9ca3af', fontSize: '0.9rem' },
  logoutButton: { padding: '8px 16px', background: 'transparent', border: '1px solid #2d3148', borderRadius: '6px', color: '#9ca3af', cursor: 'pointer', fontSize: '0.85rem' },
  addButton: { padding: '8px 16px', background: '#6366f1', border: 'none', borderRadius: '6px', color: '#fff', cursor: 'pointer', fontSize: '0.85rem', fontWeight: '600' },
  body: { padding: '32px', flex: 1 },
  pipelineSection: { marginBottom: '32px' },
  sectionTitle: { fontSize: '1.1rem', fontWeight: '600', marginBottom: '16px', color: '#e5e7eb' },
  loadingText: { color: '#4b5563', fontSize: '0.9rem' },
  pipeline: { display: 'flex', gap: '16px', overflowX: 'auto', paddingBottom: '8px' },
  stageColumn: { minWidth: '200px', flex: 1, background: '#1a1d27', borderRadius: '10px', overflow: 'hidden' },
  stageHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '12px 16px', background: '#1e2130' },
  stageLabel: { fontSize: '0.85rem', fontWeight: '600', color: '#e5e7eb' },
  stageCount: { fontSize: '0.75rem', fontWeight: '700', color: '#fff', borderRadius: '999px', padding: '2px 8px' },
  stageCards: { padding: '12px', display: 'flex', flexDirection: 'column', gap: '8px', minHeight: '80px' },
  jobCard: { background: '#0f1117', border: '1px solid #2d3148', borderRadius: '8px', padding: '12px', cursor: 'pointer' },
  jobCardCompany: { fontSize: '0.85rem', fontWeight: '600', color: '#e5e7eb', marginBottom: '4px' },
  jobCardRole: { fontSize: '0.8rem', color: '#9ca3af' },
  emptyStage: { color: '#4b5563', fontSize: '0.8rem', textAlign: 'center', padding: '16px 0' },
  widgets: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' },
  widget: { background: '#1a1d27', border: '1px solid #2d3148', borderRadius: '10px', padding: '20px' },
  widgetTitle: { fontSize: '0.95rem', fontWeight: '600', marginBottom: '16px', color: '#e5e7eb', display: 'flex', alignItems: 'center', gap: '8px' },
  widgetCount: { background: '#2d3148', borderRadius: '999px', padding: '2px 8px', fontSize: '0.75rem' },
  widgetRow: { display: 'flex', alignItems: 'center', gap: '12px', padding: '10px 0', borderBottom: '1px solid #2d3148', cursor: 'pointer' },
  widgetCompany: { fontSize: '0.85rem', fontWeight: '600', color: '#e5e7eb', minWidth: '100px' },
  widgetRole: { fontSize: '0.85rem', color: '#9ca3af', flex: 1 },
  widgetBadge: { fontSize: '0.75rem', color: '#fff', borderRadius: '999px', padding: '2px 8px', whiteSpace: 'nowrap' },
  emptyWidget: { color: '#4b5563', fontSize: '0.85rem' },
  modalOverlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.7)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000, padding: '20px' },
  modal: { background: '#1a1d27', border: '1px solid #2d3148', borderRadius: '12px', padding: '32px', width: '100%', maxWidth: '500px', maxHeight: '90vh', overflowY: 'auto' },
  modalHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '24px' },
  modalTitle: { fontSize: '1.25rem', fontWeight: '700', margin: 0 },
  modalSubtitle: { color: '#9ca3af', margin: '4px 0 0 0', fontSize: '0.9rem' },
  modalClose: { cursor: 'pointer', color: '#9ca3af', fontSize: '1.2rem', lineHeight: 1 },
  modalActions: { display: 'flex', justifyContent: 'space-between', marginTop: '8px' },
  jobLink: { display: 'inline-block', color: '#6366f1', fontSize: '0.9rem', marginBottom: '16px' },
  detailText: { color: '#9ca3af', fontSize: '0.85rem', marginBottom: '16px' },
  label: { display: 'block', fontSize: '0.85rem', color: '#9ca3af', marginBottom: '6px' },
}